#!/bin/bash
for i in {1..3}; do (echo ""; time hive -e 'select sum(total)/10000 from twpop_yp where year=107' 2>/dev/null); done
# for i in {1..3} is for i in range(3) in linux and Hdfs 
# time command will get the timpe speet for this command 
